#!/bin/sh
set -eu

# Generated by scripts/production-finalize.sh.
# Fill provider API key environment variables before running provider proof commands.
sh '/Users/jakedom/Documents/cod code/scripts/release-readiness.sh' --dist '/Users/jakedom/Documents/cod code/dist' --output-dir '/Users/jakedom/Documents/cod code/.omo/evidence/production-finalize-final/release-readiness-final'
sh '/Users/jakedom/Documents/cod code/scripts/provider-proof.sh' --provider openrouter --output-dir '/Users/jakedom/Documents/cod code/.omo/evidence/production-finalize-final/provider-proof-openrouter' --timeout-seconds 600
sh '/Users/jakedom/Documents/cod code/scripts/provider-proof.sh' --provider kimi-code --output-dir '/Users/jakedom/Documents/cod code/.omo/evidence/production-finalize-final/provider-proof-kimi-code' --timeout-seconds 600
sh '/Users/jakedom/Documents/cod code/scripts/provider-proof.sh' --provider minimax --output-dir '/Users/jakedom/Documents/cod code/.omo/evidence/production-finalize-final/provider-proof-minimax' --timeout-seconds 600
go run '/Users/jakedom/Documents/cod code/cmd/ceo-eval' --comparison-smoke --competitors '/Users/jakedom/Documents/cod code/evals/competitors.json' --output-dir '/Users/jakedom/Documents/cod code/.omo/evidence/production-finalize-final/competitor-smoke' --timeout-seconds 25
go run '/Users/jakedom/Documents/cod code/cmd/ceo-eval' --local-agent-benchmark --local-agents ceo_harness,codex_cli,opencode,pi --local-agent-benchmark-task production-core --local-agent-benchmark-repeat 1 --local-agent-benchmark-concurrency 4 --local-agent-benchmark-timeout-retries 1 --local-agent-benchmark-result-retries 1 --ceo-binary '/Users/jakedom/Documents/cod code/bin/ceo-packet' --tasks '/Users/jakedom/Documents/cod code/evals/tasks' --output-dir '/Users/jakedom/Documents/cod code/.omo/evidence/production-finalize-final/external-agent-production-core-29-final-result-retry-r1' --timeout-seconds 240 --ceo-benchmark-mode model-command --ceo-benchmark-model-command-json '["sh","/Users/jakedom/Documents/cod code/scripts/benchmark-model-command.sh"]'
sh '/Users/jakedom/Documents/cod code/scripts/production-readiness.sh' --dist '/Users/jakedom/Documents/cod code/dist' --output-dir '/Users/jakedom/Documents/cod code/.omo/evidence/production-finalize-final/production-readiness-final'
