package cli

import (
	"ceoharness/internal/ceo"
	"ceoharness/internal/history"
	"ceoharness/internal/jobpacket"
)

type options struct {
	task                                       string
	workspaceDir                               string
	artifactRoot                               string
	checkCommand                               []string
	checkCommands                              [][]string
	checkSet                                   string
	researchCommand                            []string
	jobTimeoutMS                               int
	checkAttempts                              int
	checkBackoffMS                             int
	checkFixAttempts                           int
	checkFixAttemptsSet                        bool
	requireChecks                              bool
	toolCommandTimeoutMS                       int
	ceoRevisionAttempts                        int
	ceoRevisionAttemptsSet                     bool
	maxCEOIterations                           int
	maxCEOIterationsSet                        bool
	maxSubagents                               int
	subagentConcurrency                        int
	maxToolRequests                            int
	subagents                                  []jobpacket.Subagent
	subagentAttempts                           int
	subagentBackoffMS                          int
	noProgressStop                             int
	maxContextBytes                            int
	maxSubagentOutputBytes                     int
	minSubagentConfidence                      float64
	workspaceBriefMaxFiles                     int
	workspaceBriefExcludes                     []string
	providerCostBudgetMicroUSD                 int64
	providerHealthAvoidRate                    float64
	providerHealthWatchRate                    float64
	providerHealthWatchCostPerAttemptMicroUSD  int64
	providerHealthPolicy                       history.ProviderHealthPolicy
	defaultProvider                            string
	fallbackProvider                           string
	ceoProvider                                string
	riskProviders                              map[string]string
	kindProviders                              map[string]string
	riskAreaProviders                          map[string]string
	patches                                    []ceo.PatchRequest
	approvedPreviewDigest                      string
	applyModelPatches                          bool
	previewModelPatches                        bool
	maxModelPatches                            int
	showHistory                                bool
	showReviewQueue                            bool
	reviewDetails                              bool
	showProviderHealth                         bool
	showProductionStatus                       bool
	showProductionActions                      bool
	productionActionKind                       string
	productionActionProvider                   string
	showProductionFinalize                     bool
	productionFinalizeRunComparison            bool
	productionFinalizeDist                     string
	productionFinalizeEvidenceRoot             string
	productionFinalizeProviderTimeoutSeconds   int
	productionFinalizeComparisonTimeoutSeconds int
	showConfigCheck                            bool
	showConfigDoctor                           bool
	showConfigExplain                          bool
	showConfigCompletions                      bool
	planOnly                                   bool
	showDoctor                                 bool
	doctorProviderName                         string
	showDemo                                   bool
	startDir                                   string
	showInbox                                  bool
	providerWizardPreset                       string
	repairPreset                               string
	initDemoRepoDir                            string
	showTUI                                    bool
	tuiSnapshot                                bool
	dryRun                                     bool
	writePolicy                                string
	rollbackReportPath                         string
	initConfig                                 bool
	initExampleAdapters                        bool
	adapterName                                string
	quickstartDir                              string
	showHelp                                   bool
	showAdvancedHelp                           bool
	showVersion                                bool
	interactive                                bool
	reportFormat                               reportFormat
	reportFormatSet                            bool
	modelCommand                               []string
	ceoModelCommand                            []string
	modelCommandTimeoutMS                      int
	jobID                                      string
	jobContextID                               string
	contextTraceID                             string
	priorJobContextID                          string
	jobReportID                                string
	explainFailureJobID                        string
	jobEventsID                                string
	judgeJobID                                 string
	humanVerdict                               string
	judgmentNote                               string
	rerunJobID                                 string
	rerunContextJobID                          string
	scorerFailedChecks                         []ceo.RepairFailureDetail
	continueJobID                              string
	resumeJobID                                string
	resumeAnswers                              []string
	resumeContext                              *ceo.ResumeContext
	continuation                               *ceo.ContinuationContext
	historyVerdict                             string
	historyTask                                string
	historyLimit                               int
	historySummaryOnly                         bool
	historySince                               string
	historyUntil                               string
	providerFilter                             string
	recommendationFilter                       string
	topProviders                               int
	httpInit                                   httpInitOptions
	httpInits                                  []httpInitOptions
	completionShell                            string
	completionOutputDir                        string
}
