#!/bin/sh
set -eu

# Generated by scripts/release-readiness.sh.
# This file is safe to inspect. Publishing steps stay commented until you fill real public metadata.

sh scripts/verify-release.sh --dist dist
# blocked git_remote: configure origin, for example: git remote add origin git@github.com:<owner>/<repo>.git, or export GITHUB_REPOSITORY=owner/name.
# blocked remote_release_url: export RELEASE_PUBLIC_URL=https://github.com/<owner>/<repo>/releases/tag/v<version>
# blocked github_release_assets: push a v* tag and verify release assets with RELEASE_VERSION plus GITHUB_REPOSITORY.
# blocked homebrew_formula_url: export HOMEBREW_ARCHIVE_URL=https://github.com/<owner>/<repo>/releases/download/v<version>/ceo-packet_<version>_darwin_arm64.tar.gz and rerun release-homebrew-formula.sh.
# blocked artifact_signatures: sign archives with scripts/release-signatures.sh and set RELEASE_SIGNING_PUBLIC_KEY, or document checksum-only release notes.

sh scripts/release-readiness.sh --dist dist --output-dir .omo/evidence/release-readiness-final
go run ./cmd/ceo-packet production-finalize --workspace . --dry-run
